name: example
description: A new Flutter project.

publish_to: 'none'

version: 0.0.9+2

environment:
  sdk: '>=2.15.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  vs_media_picker:
    path: ../
  provider: ^6.0.5
  photo_view: ^0.14.0
  # better_video_player: ^1.2.8
  share_plus: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true
